<a href="https://colab.research.google.com/github/ViktoriaZaremba/DataScienceCourseKNU/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Лабораторна робота №1**

1. Створити змінні базових (atomic) типів. Базові типи: character, numeric, integer, complex, logical.

In [ ]:
my_chararacter <- 'Viktoria Zaremba, UP-11'
my_numeric <- 2022
my_integer <- 1L
my_complex <- 1 + 5i
my_logical <- TRUE

In [ ]:
my_chararacter

[1] "Viktoria Zaremba, UP-11"

In [ ]:
sprintf("my_chararacter = %s; class: %s", my_chararacter, class(my_chararacter))
sprintf("my_numeric = %s; class: %s", my_numeric, class(my_numeric))
sprintf("my_integer = %s; class: %s", my_integer, class(my_integer))
sprintf("my_complex = %s; class: %s", my_complex, class(my_complex))
sprintf("my_logical = %s; class: %s", my_logical, class(my_logical))

[1] "my_chararacter = Viktoria Zaremba, UP-11; class: character"

[1] "my_numeric = 2022; class: numeric"

[1] "my_integer = 1; class: integer"

[1] "my_complex = 1+5i; class: complex"

[1] "my_logical = TRUE; class: logical"

2. Створити вектори, які: містить послідовність з 5 до 75; містить числа 3.14, 2.71, 0, 13; 100 значень TRUE.

In [ ]:
my_vec1 <- 5:75
my_vec1
class(my_vec1)

[1]  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
[26] 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
[51] 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75

[1] "integer"

In [ ]:
my_vec2 <- c(3.14, 2.71, 0, 13) 
my_vec2

[1]  3.14  2.71  0.00 13.00

In [ ]:
my_vec3_v1 <- rep(c(TRUE), 100)
my_vec3_v1

[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [46] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [61] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [76] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [91] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

In [ ]:
my_vec3_v2 <- replicate(100, c(TRUE))
my_vec3_v2

[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [46] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [61] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [76] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [91] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

In [ ]:
my_vec3_v3 <- rep(c(TRUE), times = 100)
my_vec3_v3

[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [16] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [31] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [46] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [61] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [76] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
 [91] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

3. Створити наступну матрицю за допомогою matrix, та за допомогою cbind або rbind


In [ ]:
my_matrix <- matrix(c(0.5, 3.9, 0, 2, 1.3, 131, 2.2, 7, 3.5, 2.8, 4.6, 5.1), nrow = 4, ncol = 3)
my_matrix

[,1] [,2]  [,3]
[1,] 0.5    1.3 3.5 
[2,] 3.9  131.0 2.8 
[3,] 0.0    2.2 4.6 
[4,] 2.0    7.0 5.1

In [ ]:
new_matrix <- matrix(c(0.5, 3.9, 1.3, 131.0), nrow = 2, ncol = 2)
new_matrix


[,1] [,2] 
[1,] 0.5    1.3
[2,] 3.9  131.0

In [ ]:
new_matrix <- cbind(new_matrix, c(3.5, 2.8))
new_matrix

[,1] [,2]  [,3]
[1,] 0.5    1.3 3.5 
[2,] 3.9  131.0 2.8

In [ ]:
new_matrix <- rbind(new_matrix, c(0, 2.2, 4.6))
new_matrix <- rbind(new_matrix, c(2, 7, 5.1))
new_matrix

[,1] [,2]  [,3]
[1,] 0.5    1.3 3.5 
[2,] 3.9  131.0 2.8 
[3,] 0.0    2.2 4.6 
[4,] 2.0    7.0 5.1

In [ ]:
my_matrix == new_matrix

[,1] [,2] [,3]
[1,] TRUE TRUE TRUE
[2,] TRUE TRUE TRUE
[3,] TRUE TRUE TRUE
[4,] TRUE TRUE TRUE

4. Створити довільний список (list), в який включити всі базові типи.


In [ ]:
my_list <- list(my_chararacter, my_complex, my_integer, my_logical, my_numeric)

In [ ]:
my_list

[[1]]
[1] "Viktoria Zaremba, UP-11"

[[2]]
[1] 1+5i

[[3]]
[1] 1

[[4]]
[1] TRUE

[[5]]
[1] 2022

5. Створити фактор з трьома рівнями «baby», «child», «adult».


In [ ]:
my_factor <- factor(c("baby", "child","baby", "adult", "child", "child", "adult", "adult", "adult", "child" ))
my_factor

[1] baby  child baby  adult child child adult adult adult child
Levels: adult baby child

In [ ]:
my_factor2 <- factor(c("baby", "child","baby", "child", "child", "child" ), levels = c("baby", "child", "adult"))
my_factor2

[1] baby  child baby  child child child
Levels: baby child adult

In [ ]:
length(my_factor)
length(my_factor2)


[1] 10

[1] 6

In [ ]:
my_factor[4]

[1] adult
Levels: adult baby child

6. Знайти індекс першого значення NA в векторі 1, 2, 3, 4, NA, 6, 7, NA, 9, NA, 11. Знайти кількість значень NA.

In [ ]:
new_vec = c(1, 2, 3, 4, NA, 6, 7, NA, 9, NA, 11)
new_vec

[1]  1  2  3  4 NA  6  7 NA  9 NA 11

In [ ]:
match(NA, new_vec)

[1] 5

In [ ]:
sum(is.na(new_vec))

[1] 3

7. Створити довільний data frame та вивести в консоль.


In [ ]:
df <- data.frame (
  Date = c("2022-09-09", "2022-09-10", "2022-09-11"),
  Liquidated_personnel = c(51250, 52250, 52650),
  Tanks = c(2122, 2136, 2154),
  Armoured_personnel_vehicle = c(4557, 4584, 4617)
)
df

Date       Liquidated_personnel Tanks Armoured_personnel_vehicle
1 2022-09-09 51250                2122  4557                      
2 2022-09-10 52250                2136  4584                      
3 2022-09-11 52650                2154  4617

8. Змінити імена стовпців цього data frame.


In [ ]:
colnames(df) <- c("Дата", "Особовий склад", "Танки", "Бойові броньовані машини")
df


Дата       Особовий склад Танки Бойові броньовані машини
1 2022-09-09 51250          2122  4557                    
2 2022-09-10 52250          2136  4584                    
3 2022-09-11 52650          2154  4617